### ISSUE TITLE
Update completion functions to use docker go filters instead of sed/awk

### ISSUE THREAD

**Issue by kaleb** [barnybug/docker-fish-completion#12]
On my local branch, I have separated the `__fish_print_docker_*` functions into their own files so that they can be easily tested.  I have also replaced the use of `awk` and `sed` in these functions with docker's `--format` options using `go` templating.  Are you interested in receiving these changes?

**Comment by barnybug** [comment]
I'd like to keep it a single file, but the latter change sounds promising - PR?

**Comment by kaleb** [comment]
I'll combine mine back to one file and make a PR.

**Comment by kaleb** [comment]
I finally got around to this. Submitted PR #14

**Comment by barnybug** [comment]
Fixed in PR #14
