### ISSUE TITLE
Autocompletion for container with status=Created

### ISSUE THREAD

**Issue by bdesemb** [barnybug/docker-fish-completion#19]
Hello,

Firstly, let me tell you that you did a great job. Your tool is very useful.

About my bug now,
How to reproduce:
Create a container with `docker create` command. Auto completion for `docker rm` will not work (name and ID). No problem with `docker inspect`. I am not an expert in docker so I just try these commands.

**Comment by kaleb** [comment]
Looks like a change here:

https://github.com/barnybug/docker-fish-completion/blob/master/docker.fish#L31

to something like this:

    docker ps --filter status=created --filter status=exited
